from django.urls import re_path, path, include
from OTCAPP import views
urlpatterns = [
re_path(r'MAKE',views.WHADD),
re_path(r'^SHOW$',views.WHshow),
re_path(r'DEL',views.wh_delete),
re_path(r'^SHOW/(?P<pk>[0-9]+)$', views.WH_show_specific),
re_path(r'^UPDATE/(?P<pk>[0-9]+)$', views.WHUPDATE),
re_path(r'^C$',views.PTADD),
re_path(r'^DIS$',views.PTSHOW),
re_path(r'^SPEC/(?P<pk>[0-9]+)$', views.pt_show_specific),
re_path(r'^PTSHOW$', views.pbasis),
re_path(r'^UPD/(?P<pk>[0-9]+)$', views.PTUPDATE),
re_path(r'^AD$',views.CUSTADD),
re_path(r'^BR$',views.PRODADD),
re_path(r'^SI$',views.PRODSHOW),
re_path(r'^O$',views.GOODSDADD),
re_path(r'^GOODSUPD$',views.EXCITINGUPDATE),
re_path(r'^D$',views.GOODSHOW),
re_path(r'^BANISH$',views.goods_delete),
re_path(r'^CLOCKER/(?P<pk>[0-9]+)$',views.goods_show_specific),
re_path(r'^KING/(?P<pk>[0-9]+)$',views.GOODSSPECUPDATE),
re_path(r'^ht$',views.CHshow),
re_path(r'^WHSHOWSPECIFIC$',views.WHshowspec),
re_path(r'^MONEY$',views.SALESHEADERADD),
re_path(r'^MONEY1$',views.SALESLINEERADD),
re_path(r'^CUST/(?P<pk>[0-9]+)$',views.cust_show_specific),
re_path(r'^AI/(?P<pk>[0-9]+)/(?P<gk>[0-9]+)$',views.CUSTAIUPDATE),
re_path(r'^AIUPDATE/(?P<pk>[0-9]+)/(?P<gk>[0-9]+)$',views.PRODNEWUPDATE),
re_path(r'^SALESBABY$',views.SALESSHOW),
re_path(r'^SALESSPECIFYINGLY/(?P<pk>[0-9]+)$',views.SALESSPECIFYSHOW),
re_path(r'^NAHFAM/(?P<pk>[0-9]+)$',views.SALESSHOWPK),
re_path(r'^BEATSLAPPING/(?P<pk>[0-9]+)/(?P<gk>[0-9]+)$',views.SALESHEADERNEWUPDATE),
re_path(r'^DOUBLETROUBLE/(?P<pk>[0-9]+)/(?P<gk>[0-9]+)/(?P<hk>[0-9]+)/(?P<sk>[0-9]+)/(?P<jk>[0-9]+)/(?P<lk>[0-9]+)$',views.SALESINLINeSHOWPK)
]