# Generated by Django 2.2.5 on 2022-01-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WHOUSE',
            fields=[
                ('WHCODE', models.AutoField(default='', max_length=3, primary_key=True, serialize=False)),
                ('WHNAME', models.CharField(default='', max_length=25)),
                ('WHADD', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
