# Generated by Django 2.2.5 on 2022-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0002_auto_20220112_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYTERM',
            fields=[
                ('PTERMCODE', models.AutoField(default='', max_length=4, primary_key=True, serialize=False)),
                ('PTDESC', models.CharField(default='', max_length=25)),
                ('PTDAYS', models.PositiveIntegerField()),
                ('PTBASIS', models.CharField(default='', max_length=25)),
            ],
            options={
                'ordering': ('PTERMCODE',),
            },
        ),
    ]
