# Generated by Django 2.2.5 on 2022-01-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0004_delete_payterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYTERM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PTBASIS',
            fields=[
                ('BASISCODE', models.AutoField(primary_key=True, serialize=False)),
                ('BASISDESC', models.CharField(default='', max_length=25)),
            ],
            options={
                'ordering': ('BASISCODE',),
            },
        ),
    ]
