# Generated by Django 2.2.5 on 2022-01-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0005_payterm_ptbasis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PAYTERM',
        ),
    ]
