# Generated by Django 2.2.5 on 2022-01-14 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0006_delete_payterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYTERM',
            fields=[
                ('PTERMCODE', models.AutoField(default='', max_length=4, primary_key=True, serialize=False)),
                ('PTDESC', models.CharField(default='', max_length=25)),
                ('PTDAYS', models.PositiveIntegerField()),
                ('PTBASISCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTCAPP.PTBASIS')),
            ],
            options={
                'ordering': ('PTERMCODE',),
            },
        ),
    ]
