# Generated by Django 2.2.5 on 2022-01-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0009_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PRODUCT',
        ),
    ]
