# Generated by Django 2.2.5 on 2022-01-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0011_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='INVENT',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='INVENTCOST',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='ONORDERQTY',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
