# Generated by Django 2.2.5 on 2022-01-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0013_goodreciept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GOODRECIEPT',
        ),
    ]
