# Generated by Django 2.2.5 on 2022-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0015_goodreciept'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHANGE',
            fields=[
                ('CHANGENO', models.AutoField(default='', max_length=10, primary_key=True, serialize=False)),
                ('BATCHNO', models.CharField(default='', max_length=6)),
                ('FIELDNAME', models.CharField(default='', max_length=600)),
                ('OLDVALUE', models.CharField(default='', max_length=600)),
                ('NEWVALUE', models.CharField(default='', max_length=600)),
                ('CHANGEDATE', models.DateTimeField()),
                ('USER', models.CharField(default='', max_length=50)),
            ],
            options={
                'ordering': ('CHANGENO',),
            },
        ),
    ]
