# Generated by Django 2.2.5 on 2022-01-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0016_change'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CUSTOMER',
        ),
    ]
