# Generated by Django 2.2.5 on 2022-01-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0017_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('CUSTCODE', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('CUSTNAME', models.CharField(default='', max_length=25)),
                ('CUSTADD', models.CharField(default='', max_length=25)),
                ('PTERMCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTCAPP.PAYTERM')),
                ('WHCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTCAPP.WHOUSE')),
            ],
        ),
    ]
