# Generated by Django 2.2.5 on 2022-01-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0019_salesheader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salesheader',
        ),
    ]
