# Generated by Django 2.2.5 on 2022-01-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0020_delete_salesheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesheader',
            fields=[
                ('SONUM', models.AutoField(default='', max_length=6, primary_key=True, serialize=False)),
                ('SODATE', models.DateField(default='', max_length=10)),
                ('RDD', models.DateField(default='', max_length=10)),
                ('ORDERAMT', models.IntegerField(default='')),
                ('CUSTCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTCAPP.CUSTOMER')),
                ('PTERM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTCAPP.PAYTERM')),
            ],
        ),
    ]
