# Generated by Django 2.2.5 on 2022-01-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0022_salesinline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salesinline',
        ),
    ]
