# Generated by Django 2.2.5 on 2022-01-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0025_delete_salesinline'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesinline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SONUM', models.IntegerField(default='')),
                ('ITEM', models.IntegerField(default='')),
                ('QTY', models.IntegerField(default='')),
                ('PRICE', models.IntegerField(default='')),
                ('STATUS', models.CharField(default='', max_length=10)),
                ('PRODCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTCAPP.PRODUCT')),
                ('WAREH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTCAPP.WHOUSE')),
            ],
        ),
    ]
