# Generated by Django 2.2.5 on 2022-01-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTCAPP', '0026_salesinline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesheader',
            name='CUSTCODE',
        ),
        migrations.RemoveField(
            model_name='salesheader',
            name='PTERM',
        ),
        migrations.DeleteModel(
            name='CUSTOMER',
        ),
        migrations.DeleteModel(
            name='salesheader',
        ),
    ]
